### ISSUE TITLE
NegativeArraySizeException occurs when an EventDispatcher is generated for an EventHandler with long or double parameters

### ISSUE THREAD

**Issue by kKdH** [jayware/entity-essentials#14]
```
java.lang.NegativeArraySizeException
    at org.objectweb.asm.Frame.a(Unknown Source)
    at org.objectweb.asm.MethodWriter.visitMaxs(Unknown Source)
    at org.jayware.e2.event.impl.EventDispatcherFactoryImpl.createEventDispatcher(EventDispatcherFactoryImpl.java:461)
    at org.jayware.e2.event.impl.EventDispatcherFactoryImpl.createTargetDescription(EventDispatcherFactoryImpl.java:159)
    at org.jayware.e2.event.impl.EventDispatcherFactoryImpl.createEventDispatcher(EventDispatcherFactoryImpl.java:134)
    at org.jayware.e2.event.impl.EventDispatcherFactoryImplTest.test_createEventDispatcher_ForHandlerWithPrimitiveParameter(EventDispatcherFactoryImplTest.java:116)
```

**Comment by marekadare** [comment]
Wenn man den Test nur mit long-param ausführt kommt diese exception hier:

```
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    org/jayware/e2/event/generated/EventDispatcher_TestHandler_WithPrimitiveParameter_DFB794A1.dispatch(Lorg/jayware/e2/event/api/Event;Ljava/lang/Object;)V @107: invokevirtual
  Reason:
    Type 'java/lang/Long' (current frame, stack[1]) is not assignable to 'java/lang/Integer'
  Current Frame:
    bci: @107
    flags: { }
    locals: { 'org/jayware/e2/event/generated/EventDispatcher_TestHandler_WithPrimitiveParameter_DFB794A1', 'org/jayware/e2/event/api/Event', 'java/lang/Object', 'org/jayware/e2/event/impl/EventDispatcherFactoryImplTest$TestHandler_WithPrimitiveParameter', 'java/lang/Object' }
    stack: { 'org/jayware/e2/event/impl/EventDispatcherFactoryImplTest$TestHandler_WithPrimitiveParameter', 'java/lang/Long' }
  Bytecode:
    0x0000000: 1219 2cb6 001d b600 2399 0068 2cc0 0019
    0x0000010: 4e2b 1225 b900 2b02 0099 0058 2b12 2db9
    0x0000020: 0031 0200 9a00 10b2 0012 1233 b900 3902
    0x0000030: 00a7 0040 2b12 2db9 003d 0200 3a04 1904
    0x0000040: c700 10b2 0012 123f b900 3902 00a7 0024
    0x0000050: 1904 c100 419a 0010 b200 1212 43b9 0039
    0x0000060: 0200 a700 0f2d 1904 c000 41b6 0049 b600
    0x0000070: 4db1                                   
  Stackmap Table:
    append_frame(@52,Object[#25])
    append_frame(@80,Object[#4])
    same_frame(@101)
    chop_frame(@113,2)


    at java.lang.Class.getDeclaredConstructors0(Native Method)
    at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
    at java.lang.Class.getConstructor0(Class.java:3075)
    at java.lang.Class.newInstance(Class.java:412)
    at org.jayware.e2.event.impl.EventDispatcherFactoryImpl.createEventDispatcher(EventDispatcherFactoryImpl.java:513)
    at org.jayware.e2.event.impl.EventDispatcherFactoryImpl.createTargetDescription(EventDispatcherFactoryImpl.java:162)
    at org.jayware.e2.event.impl.EventDispatcherFactoryImpl.createEventDispatcher(EventDispatcherFactoryImpl.java:137)
    at org.jayware.e2.event.impl.EventDispatcherFactoryImplTest.test_createEventDispatcher_ForHandlerWithPrimitiveParameter(EventDispatcherFactoryImplTest.java:116)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
    at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
    at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
    at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
    at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
    at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
    at org.testng.TestRunner.privateRun(TestRunner.java:782)
    at org.testng.TestRunner.run(TestRunner.java:632)
    at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
    at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
    at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
    at org.testng.SuiteRunner.run(SuiteRunner.java:268)
    at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
    at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
    at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
    at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
    at org.testng.TestNG.run(TestNG.java:1064)
    at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:74)
    at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:121)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

```

**Comment by marekadare** [comment]
Und nur double-param geht ohne exceptions

**Comment by kKdH** [comment]
Could you post the pice of code you used to reproduce the issue?

**Comment by marekadare** [comment]
I commented out the other params in the EventDispatcherFactoryImplTest.java for the test_createEventDispatcher_ForHandlerWithPrimitiveParameter() test like this:

``` java
public static class TestHandler_WithPrimitiveParameter
{
//        @Handle(TestEventTypeA.class)
//        public void handle(@Param("boolean-param") boolean param) {}
//
//        @Handle(TestEventTypeA.class)
//        public void handle(@Param("byte-param") byte param) {}
//
//        @Handle(TestEventTypeA.class)
//        public void handle(@Param("short-param") short param) {}
//
//        @Handle(TestEventTypeA.class)
//        public void handle(@Param("int-param") int param) {}

        @Handle(TestEventTypeA.class)
        public void handle(@Param("long-param") long param) {}

//        @Handle(TestEventTypeA.class)
//        public void handle(@Param("float-param") float param) {}

//        @Handle(TestEventTypeA.class)
//        public void handle(@Param("double-param") double param) {}
}
```
